// AdBlockPlus.idl : IDL source for AdblockPlus.dll
//

#include "AdblockPlusGuids.h"

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(GUUID_IPRODUCT),
	dual,
	helpstring("Adblock Plus Interface"),
	pointer_default(unique)
]
interface IIEPlugin : IDispatch
{
};

[
	uuid(GUUID_TYPELIB),
	version(1.0),
	helpstring("Adblock Plus 1.0 Type Library")
]

library PluginLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(GUUID_CLASS_PRODUCT),
		helpstring("Adblock Plus Class")
	]
	coclass PluginClass
	{
		[default] interface IIEPlugin;
	};
};
