#ifndef IEPLUGIN_VERSION
#define IEPLUGIN_VERSION L"1.0"
#endif

#ifndef VERSIONINFO_VERSION
#define VERSIONINFO_VERSION 1,0,0,0
#endif

#ifndef VERSIONINFO_VERSION_STR
#define VERSIONINFO_VERSION_STR "1.0.0.0"
#endif
